---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

language: shell
os: linux
git:
  depth: 1
dist: bionic
cache:
  directories:
    - /home/travis/.vagrant.d/boxes
script:
  - RUN_LONG_TESTS=true SUDO_VAGRANT_CMD=true ./check.sh
env:
  - VAGRANT_NAME=ubuntu_xenial
  - VAGRANT_NAME=centos_7
  - VAGRANT_NAME=opensuse
  - VAGRANT_NAME=centos_8
  - VAGRANT_NAME=ubuntu_bionic
  - VAGRANT_NAME=ubuntu_focal
jobs:
  include:
    - name: CentOS 7 - Short tests
      script:
        - ./check.sh
      env:
        - SUDO_VAGRANT_CMD=true
        - PKG_DRIVER=kvm
        - VAGRANT_NAME=centos_7
