---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

language: shell
os: linux
git:
  depth: 1
dist: bionic
cache:
  directories:
    - /home/travis/.vagrant.d/boxes
script:
  - ./check.sh
env:
  - VAGRANT_NAME=ubuntu_xenial
  - VAGRANT_NAME=centos_7
  - VAGRANT_NAME=opensuse
  - VAGRANT_NAME=centos_8
  - VAGRANT_NAME=ubuntu_bionic
  - VAGRANT_NAME=ubuntu_focal
jobs:
  include:
    - name: Lint validation
      install:
        - curl -fsSL http://bit.ly/install_pkg | PKG="tox" bash
      script:
        - tox -e lint
        - bash -c 'shopt -s globstar; shellcheck -x **/*.sh'
