# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Install and configure tools required for the CI check composite task
inputs:
  vagrant_name:
    description: "Operating system and release number to be used during the test"
    default: ubuntu_xenial
runs:
  using: "composite"
  steps:
    - name: Cache Vagrant boxes
      uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # 4.2.1
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ inputs.vagrant_name }}-${{ hashFiles('distros_supported.yml') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-${{ inputs.vagrant_name }}-
    - name: Apply workaround for VBoxHeadless issue on macOS (https://www.virtualbox.org/ticket/20636)
      shell: bash
      run: |
        if [[ "$(VBoxManage --version)" == "6.1.28r147628" ]]; then
            find . -type f -iname "Vagrantfile" -exec sed -i 's|v.gui = .*|v.gui = true|g' {} \;
        fi
    - name: Install Vagrant Reload plugin
      shell: bash
      run: vagrant plugin install vagrant-reload
