---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check Test Exceptions
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'master'

jobs:
  check:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: opensuse
            test: docker
          - os: ubuntu_focal
            test: nodejs
    steps:
      - uses: actions/checkout@v2
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - name: Replace shorten links
        run: find . -type f -iname "*sh" -exec sed -i '.bak' 's|http://bit.ly/install_pkg|https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/install.sh|g' {} \;
      - name: Run integration tests
        env:
          VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
          CPUS: 2
          MEMORY: 12288
          VAGRANT_NAME: ${{ matrix.os }}
          TEST: ${{ matrix.test }}
        run: cd ./scripts/${TEST}; vagrant up ${VAGRANT_NAME}
