---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Lint Code Base
# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  get-sloc:
    name: Count Lines of Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Setup Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: '>=1.20.0'
      - name: Install dependencies
        run: go install github.com/boyter/scc/v3@latest
      - name: Run scc tool
        run: scc --format wide
  check-broken-links:
    name: Check URL broken links into documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Check broken links
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
  check-super-linter:
    name: Run GitHub super-linter tool for verify quality of code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Check super-linter
        uses: github/super-linter@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          KUBERNETES_KUBEVAL_OPTIONS: "--ignore-missing-schemas"
          KUBERNETES_KUBECONFORM_OPTIONS: '-ignore-missing-schemas'
  check-tox:
    name: Run additional linter tools from python tox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Install tox
        run: pip install tox
      - name: Run tox validation
        run: tox -e lint
