---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Lint Code Base
# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  check-broken-links:
    name: Check URL broken links into documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check broken links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
  check-super-linter:
    name: Run GitHub super-linter tool for verify quality of code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check super-linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          VALIDATE_KUBERNETES_KUBEVAL: false
  check-tox:
    name: Run additional linter tools from python tox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tox
        run: pip install tox
      - name: Run tox validation
        run: tox -e lint
