# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Lint Code Base
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  get-sloc:
    name: Count Lines of Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Setup Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # 5.3.0
        with:
          go-version: ">=1.20.0"
      - name: Install dependencies
        run: go install github.com/boyter/scc/v3@latest
      - name: Run scc tool
        run: scc --format wide
  check-broken-links:
    name: Check URL broken links into documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Check broken links
        uses: gaurav-nelson/github-action-markdown-link-check@636e17b35a5803e014b7272d9e46a8262705416a # 1.0.16
  check-super-linter:
    name: Run GitHub super-linter tool for verify quality of code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Check super-linter
        uses: github/super-linter@b807e99ddd37e444d189cfd2c2ca1274d8ae8ef1 # 7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          KUBERNETES_KUBEVAL_OPTIONS: "--ignore-missing-schemas"
          KUBERNETES_KUBECONFORM_OPTIONS: "-ignore-missing-schemas"
  check-tox:
    name: Run additional linter tools from python tox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Install tox
        run: pip install tox
      - name: Run tox validation
        run: tox -e lint
