---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check All - Drivers Profile
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - 'scripts/qat-driver/*'
      - '!**.md'
  pull_request_review:
    types:
      - submitted
    paths:
      - 'scripts/qat-driver/*'
      - '!**.md'

jobs:
  check:
    runs-on: macos-10.15
    if: >-
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      ) ||
      github.event_name != 'pull_request_review'
    strategy:
      fail-fast: false
      matrix:
        name: [ubuntu_xenial, ubuntu_focal, ubuntu_bionic, centos_7, opensuse_leap]
    steps:
      - uses: actions/checkout@v2
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ matrix.name }}-${{ hashFiles('distros_supported.yml') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-${{ matrix.name }}-
      - name: Install Vagrant Reload plugin
        run: vagrant plugin install vagrant-reload
      - name: Install GNU tools
        run: brew install proctools iproute2mac
      - name: Run integration tests
        env:
          VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
          VAGRANT_NAME: ${{ matrix.name }}
          PROFILE: drivers
          MEMORY: 12288
        run: ./ci/check.sh
      - name: Check HW resources
        if: failure()
        run: |
          vm_stat
          top -l 1 -n 0
          VBoxManage list runningvms --long
      - name: Check VM logs
        if: failure()
        shell: bash
        run: |
          running_vm_info=$(vagrant global-status --prune | grep running)
          if [ "$running_vm_info" ]; then
              cd "$(echo "$running_vm_info" | awk '{ print $NF}')"
              vagrant ssh "$(echo "$running_vm_info" | awk '{ print $2 }')" -- "cat ~/*.log"
          fi
      - name: Check All logs
        if: always()
        run: cat /tmp/check_*.log
