---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check All - DevOps Profile
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - 'scripts/act/*'
      - 'scripts/docker/*'
      - 'scripts/fly/*'
      - 'scripts/terraform/*'
      - 'scripts/vagrant/*'
      - '!**.md'
  pull_request_review:
    types:
      - submitted
    paths:
      - ci/pinned_versions.env
      - 'scripts/act/*'
      - 'scripts/docker/*'
      - 'scripts/fly/*'
      - 'scripts/terraform/*'
      - 'scripts/vagrant/*'
      - '!**.md'

jobs:
  check-devops:
    name: Run devops profile on all supported Linux distros
    runs-on: macos-10.15
    if: >-
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      ) ||
      github.event_name != 'pull_request_review'
    strategy:
      fail-fast: false
      matrix:
        name: [ubuntu_xenial, ubuntu_focal, ubuntu_bionic, centos_8, centos_7, opensuse_tumbleweed, opensuse_leap]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/check
        with:
          vagrant_name: ${{ matrix.name }}
          profile: devops
