---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check All
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  check:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        name: [ubuntu_xenial, ubuntu_focal, ubuntu_bionic, centos_8, centos_7, opensuse]
        profile: [main, cloud, devops, drivers, lang, utils, virt]
    steps:
      - uses: actions/checkout@v2
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - name: Install Vagrant Reload plugin
        run: vagrant plugin install vagrant-reload
      - name: Install GNU tools
        run: brew install proctools iproute2mac
      - name: Replace shorten links
        run: find . -type f -iname "*sh" -exec sed -i '.bak' 's|http://bit.ly/install_pkg|https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/install.sh|g' {} \;
      - name: Run integration tests
        env:
          VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
          CPUS: 1
          MEMORY: 4096
          VAGRANT_NAME: ${{ matrix.name }}
          PROFILE: ${{ matrix.profile }}
        run: ./check.sh
      - name: Check memory
        if: failure()
        run: vm_stat | awk '/Pages free/ {print $3 * 4 }'
      - name: Check VMs
        if: failure()
        run: |
          vagrant global-status --prune
          VBoxManage list vms
      - name: Check logs
        if: failure()
        run: cat /tmp/check_*.log
