---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check All - Virtualization Profile
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - pinned_versions.env
      - 'scripts/libvirt/*'
      - 'scripts/qemu/*'
      - 'scripts/virtualbox/*'
      - '!**.md'
  pull_request:
    branches:
      - master
    paths:
      - pinned_versions.env
      - 'scripts/libvirt/*'
      - 'scripts/qemu/*'
      - 'scripts/virtualbox/*'
      - '!**.md'

jobs:
  check:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        name: [ubuntu_xenial, ubuntu_focal, ubuntu_bionic, centos_8, centos_7, opensuse]
    steps:
      - uses: actions/checkout@v2
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - name: Install Vagrant Reload plugin
        run: vagrant plugin install vagrant-reload
      - name: Install GNU tools
        run: brew install proctools iproute2mac
      - name: Run integration tests
        env:
          VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
          VAGRANT_NAME: ${{ matrix.name }}
          PROFILE: virt
          MEMORY: 12288
        run: ./check.sh
      - name: Check HW resources
        if: failure()
        run: |
          vm_stat
          top -l 1 -n 0
          VBoxManage list runningvms --long
      - name: Check VM logs
        if: failure()
        shell: bash
        run: |
          read -a running_vm <<< $(vagrant global-status --prune | grep running)
          if [[ -n $running_vm ]]; then
              cd ${running_vm[4]}
              vagrant ssh ${running_vm[1]} -- "cat ~/*.log"
          fi
      - name: Check All logs
        if: always()
        run: cat /tmp/check_*.log
