---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check All
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '**.sh'
  pull_request_review:
    types:
      - submitted

jobs:
  check-format:
    name: Check scripts format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: -i 4 -s
        with:
          sh_checker_shellcheck_disable: true
  check-shellspec:
    name: Run BDD shell specs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Install ShellSpec
        run: curl -fsSL https://github.com/shellspec/shellspec/releases/latest/download/shellspec-dist.tar.gz | tar -xz -C ..
      - name: Run Shellspec
        shell: bash
        run: ../shellspec/shellspec
  changes:
    runs-on: ubuntu-latest
    if: >-
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      ) ||
      github.event_name != 'pull_request_review'
    outputs:
      scripts: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: dorny/paths-filter@v2.11.1
        if: ${{ !env.ACT }}
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            versions: &versions
              - ci/pinned_versions.env
            main:
              - *versions
              - '*.sh'
            aws:
              - *versions
              - 'src/aws/*'
            cni-plugins:
              - *versions
              - 'src/cni-plugins/*'
            helm:
              - *versions
              - 'src/helm/*'
            kn:
              - *versions
              - 'src/kn/*'
            kind:
              - *versions
              - 'src/kind/*'
            kubectl:
              - *versions
              - 'src/kubectl/*'
            kustomize:
              - *versions
              - 'src/kustomize/*'
            podman:
              - *versions
              - 'src/podman/*'
            skopeo:
              - *versions
              - 'src/skopeo/*'
            tkn:
              - *versions
              - 'src/tkn/*'
            act:
              - *versions
              - 'src/act/*'
            docker:
              - *versions
              - 'src/docker/*'
            fly:
              - *versions
              - 'src/fly/*'
            terraform:
              - *versions
              - 'src/terraform/*'
            vagrant:
              - *versions
              - 'src/vagrant/*'
            qat-driver:
              - *versions
              - 'src/qat-driver/*'
            crystal-lang:
              - *versions
              - 'src/crystal-lang/*'
            go-lang:
              - *versions
              - 'src/go-lang/*'
            nodejs:
              - *versions
              - 'src/nodejs/*'
            rust-lang:
              - *versions
              - 'src/rust-lang/*'
            gomplate:
              - *versions
              - 'src/gomplate/*'
            hadolint:
              - *versions
              - 'src/hadolint/*'
            nfs:
              - *versions
              - 'src/nfs/*'
            pip:
              - *versions
              - 'src/pip/*'
            yq:
              - *versions
              - 'src/yq/*'
            libvirt:
              - *versions
              - 'src/libvirt/*'
            qemu:
              - *versions
              - 'src/qemu/*'
            virtualbox:
              - *versions
              - 'src/virtualbox/*'
  generate-matrix:
    name: Generate the Test matrix for vagrant and devcontainers
    runs-on: ubuntu-latest
    needs:
      - changes
    outputs:
      matrix-alias: ${{ steps.set-matrices.outputs.matrix-alias }}
      matrix-image: ${{ steps.set-matrices.outputs.matrix-image }}
    steps:
      - uses: actions/checkout@v3.1.0
      - id: set-matrices
        run: ./ci/generate_matrix.sh '${{ needs.changes.outputs.scripts }}'
  check-vagrant:
    name: Run vagrant validation for all supported Linux distros
    runs-on: macos-12
    needs:
      - generate-matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix-alias) }}
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/check-vagrant
        with:
          vagrant_name: ${{ matrix.name }}
          script: ${{ matrix.script }}
  check-devcontainer:
    name: Run devcontainer validation for all supported Linux distros
    runs-on: ubuntu-latest
    needs:
      - generate-matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix-image) }}
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli
      - name: Generating tests for '${{ matrix.script }}'
        run: |
          rm -f test/${{ matrix.script }}/test.sh
          cp src/${{ matrix.script }}/validate.sh test/${{ matrix.script }}/test.sh
          devcontainer features test --skip-scenarios -f ${{ matrix.script }} -i ${{ matrix.image }} .
